### ISSUE TITLE
Diamond Chips from OC Recipe Bug

### ISSUE THREAD

**Issue by Pr0tatoCode** [MercyDirective/BloodAndGears#4]
When crafting diamond chips from OpenComputers, it says 1 diamond anywhere in the crafting grid will make 6 diamond chips. When doing so though, it shows that you get a Weather Crystal from EnderIO.
https://imgur.com/a/tTAx1 (proof)

**Comment by MercyDirective** [comment]
Partially resolved. Shop signs added to spawn.
